# Generated by Django 5.2.7 on 2026-03-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre du Document')),
                ('file', models.FileField(upload_to='documents_ia/', verbose_name='Fichier PDF')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_indexed', models.BooleanField(default=False, verbose_name="Indexé par l'IA")),
            ],
        ),
    ]
