# Generated by Django 5.2.7 on 2026-03-02 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_users', '0014_enlarge_codeqr_code_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=180, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('objectifs', models.TextField(blank=True, null=True)),
                ('prerequis', models.TextField(blank=True, null=True)),
                ('duree_heures', models.PositiveIntegerField(default=0)),
                ('format', models.CharField(choices=[('presentiel', 'Présentiel'), ('distanciel', 'Distanciel'), ('hybride', 'Hybride')], default='presentiel', max_length=20)),
                ('cout', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='SessionFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('lieu', models.CharField(blank=True, max_length=180, null=True)),
                ('capacite', models.PositiveIntegerField(default=0)),
                ('formateur', models.CharField(blank=True, max_length=180, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('ouverte', 'Ouverte aux inscriptions'), ('cloturee', 'Clôturée'), ('annulee', 'Annulée')], default='planifiee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='manage_contrat.formation')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='DemandeFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente validation manager'), ('manager_valide', 'Validée manager'), ('rh_valide', 'Validée RH'), ('confirme', 'Confirmée'), ('liste_attente', "Liste d'attente"), ('rejete', 'Rejetée'), ('annule', 'Annulée')], default='en_attente', max_length=20)),
                ('motif', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_formation_creees', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_formation_decidees', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_formation', to='manage_users.employe')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='manage_contrat.sessionformation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sessionformation',
            index=models.Index(fields=['formation', 'date_debut'], name='session_formation_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeformation',
            index=models.Index(fields=['session', 'statut'], name='demande_session_statut_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='demandeformation',
            unique_together={('employe', 'session')},
        ),
    ]
