# Generated by Django 5.2.7 on 2026-03-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contrat', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sessionformation',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__gte', models.F('date_debut'))), name='session_dates_coherentes'),
        ),
        migrations.AddConstraint(
            model_name='sessionformation',
            constraint=models.CheckConstraint(condition=models.Q(('capacite__gte', 1)), name='session_capacite_positive'),
        ),
    ]
