# Generated by Django 5.2.7 on 2026-03-02 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_contrat', '0002_sessionformation_session_dates_coherentes_and_more'),
        ('manage_users', '0014_enlarge_codeqr_code_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('type_contrat', models.CharField(choices=[('cdi', 'CDI'), ('cdd', 'CDD'), ('stage', 'Stage'), ('prestation', 'Prestation')], max_length=20)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_signature', 'En signature'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('clos', 'Clos')], default='brouillon', max_length=20)),
                ('lieu_travail', models.CharField(blank=True, max_length=180, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('temps_travail_pct', models.PositiveIntegerField(default=100)),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devise', models.CharField(default='XAF', max_length=8)),
                ('periodicite', models.CharField(default='mensuel', max_length=20)),
                ('horaire_hebdo_heures', models.PositiveIntegerField(default=40)),
                ('conges_annuels_jours', models.PositiveIntegerField(default=30)),
                ('periode_essai_mois', models.PositiveIntegerField(default=0)),
                ('preavis_jours', models.PositiveIntegerField(default=0)),
                ('avantages', models.TextField(blank=True, null=True)),
                ('clauses_particulieres', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='contrats/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_crees', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='manage_users.employe')),
                ('poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manage_users.poste')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employe', 'statut'], name='contrat_employe_statut_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__isnull', True), ('type_contrat__in', ['cdd', 'stage', 'prestation']), _negated=True), name='contrat_duree_daterange'), models.CheckConstraint(condition=models.Q(('temps_travail_pct__gte', 1), ('temps_travail_pct__lte', 200)), name='contrat_temps_travail_range')],
            },
        ),
    ]
