# Generated by Django 5.2.7 on 2025-11-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('admin', 'Administrateur'), ('employee', 'Employé')], default='employee', max_length=20),
        ),
    ]
