# Generated by Django 5.2.7 on 2025-11-28 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0004_demandeconge_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCongeAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approuve', 'Approuvée'), ('rejete', 'Rejetée'), ('modifiee', 'Modifiée')], max_length=20)),
                ('raison', models.TextField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_audit', to=settings.AUTH_USER_MODEL)),
                ('demande_conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='manage_users.demandeconge')),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
    ]
