# Generated by Django 5.2.7 on 2025-11-28 13:32

import django.db.models.deletion
from django.db import migrations, models


def create_default_departement(apps, schema_editor):
    """Créer un département par défaut pour les postes existants"""
    Departement = apps.get_model('manage_users', 'Departement')
    # Créer un département par défaut s'il n'existe pas
    if not Departement.objects.exists():
        Departement.objects.create(nom='Général', description='Département par défaut')


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0005_demandecongeaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        # Ajouter d'abord le champ en nullable
        migrations.AddField(
            model_name='poste',
            name='departement',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='manage_users.departement'),
        ),
        # Créer le département par défaut
        migrations.RunPython(create_default_departement),
        # Maintenant mettre à jour les postes existants pour référencer le département
        migrations.RunSQL(
            "UPDATE manage_users_poste SET departement_id = 1 WHERE departement_id IS NULL"
        ),
        # Enfin, rendre le champ non-nullable
        migrations.AlterField(
            model_name='poste',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes', to='manage_users.departement'),
        ),
        migrations.AlterModelOptions(
            name='poste',
            options={'ordering': ['departement', 'titre']},
        ),
    ]
