# Generated by Django 5.2.7 on 2025-11-28 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0006_add_departement_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='chef_departement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departement_manage', to='manage_users.employe'),
        ),
    ]
