# Generated by Django 5.2.7 on 2025-12-10 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0008_codeqr_badgeage_presence_rapportpresence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeqr',
            name='employe',
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='presence',
            name='employe',
        ),
        migrations.AlterUniqueTogether(
            name='rapportpresence',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rapportpresence',
            name='employe',
        ),
        migrations.DeleteModel(
            name='Badgeage',
        ),
        migrations.DeleteModel(
            name='CodeQR',
        ),
        migrations.DeleteModel(
            name='Presence',
        ),
        migrations.DeleteModel(
            name='RapportPresence',
        ),
    ]
