# Generated by Django 5.2.7 on 2025-12-10 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0010_readd_badgeage_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rapportpresence',
            name='manage_user_rapport_idx',
        ),
        migrations.RenameIndex(
            model_name='badgeage',
            new_name='manage_user_employe_3e4acc_idx',
            old_name='manage_user_employe_date_badge_idx',
        ),
        migrations.RenameIndex(
            model_name='badgeage',
            new_name='manage_user_date_371956_idx',
            old_name='manage_user_badge_date_idx',
        ),
        migrations.RenameIndex(
            model_name='presence',
            new_name='manage_user_employe_111ba5_idx',
            old_name='manage_user_employe_date_idx',
        ),
        migrations.RenameIndex(
            model_name='presence',
            new_name='manage_user_date_77b359_idx',
            old_name='manage_user_date_statut_idx',
        ),
    ]
