# Generated by Cascade on 2026-02-06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0012_remove_codeqr_employe_alter_presence_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_unique', models.CharField(db_index=True, max_length=100, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code_qr', to='manage_users.employe')),
            ],
            options={
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('statut', models.CharField(choices=[('present', 'Présent'), ('absent', 'Absent'), ('retard', 'En retard'), ('conge', 'Congé'), ('repos', 'Jour de repos')], default='absent', max_length=20)),
                ('heure_arrivee', models.TimeField(blank=True, null=True)),
                ('heure_depart', models.TimeField(blank=True, null=True)),
                ('duree_travail_minutes', models.IntegerField(default=0)),
                ('nb_pauses', models.IntegerField(default=0)),
                ('duree_pauses_minutes', models.IntegerField(default=0)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='manage_users.employe')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': (('employe', 'date'),),
            },
        ),
        migrations.CreateModel(
            name='RapportPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('total_jours_travail', models.IntegerField(default=0)),
                ('total_jours_present', models.IntegerField(default=0)),
                ('total_jours_absent', models.IntegerField(default=0)),
                ('total_jours_retard', models.IntegerField(default=0)),
                ('total_jours_conge', models.IntegerField(default=0)),
                ('total_jours_repos', models.IntegerField(default=0)),
                ('total_heures_travail', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_heures_pauses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observations', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports_presence', to='manage_users.employe')),
            ],
            options={
                'ordering': ['-annee', '-mois'],
                'unique_together': (('employe', 'annee', 'mois'),),
            },
        ),
        migrations.CreateModel(
            name='Badgeage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('arrivee', 'Arrivée'), ('depart', 'Départ'), ('pause_debut', 'Début de pause'), ('pause_fin', 'Fin de pause')], max_length=20)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True, db_index=True)),
                ('localisation_latitude', models.FloatField(blank=True, null=True)),
                ('localisation_longitude', models.FloatField(blank=True, null=True)),
                ('adresse_localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badgeages', to='manage_users.employe')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['employe', 'date'], name='manage_user_employe_date_idx'),
        ),
        migrations.AddIndex(
            model_name='presence',
            index=models.Index(fields=['date', 'statut'], name='manage_user_date_statut_idx'),
        ),
        migrations.AddIndex(
            model_name='rapportpresence',
            index=models.Index(fields=['employe', 'annee', 'mois'], name='manage_user_rapport_idx'),
        ),
        migrations.AddIndex(
            model_name='badgeage',
            index=models.Index(fields=['employe', 'date'], name='mu_emp_date_bdg_idx'),
        ),
        migrations.AddIndex(
            model_name='badgeage',
            index=models.Index(fields=['date'], name='manage_user_badge_date_idx'),
        ),
    ]
