# Generated by Django 5.2.7 on 2026-02-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0013_readd_badgeage_presence_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeqr',
            name='code_unique',
            field=models.CharField(db_index=True, max_length=512, unique=True),
        ),
    ]
