# Generated by Django 5.2.7 on 2026-02-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_users', '0015_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='formateur',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
